export const SELECT_FOLDER = "SELECT_FOLDER"
export const ADD_FOLDER = "ADD_FOLDER"
export const DELETE_FOLDER = "DELETE_FOLDER"
export const RENAME_FOLDER = "RENAME_FOLDER"

export const SELECT_NOTE = "SELECT_NOTE"
export const ADD_NOTE = "ADD_NOTE"
export const DELETE_NOTE = "DELETE_NOTE"
export const MOVE_NOTE_TO_TRASH = "MOVE_NOTE_TO_TRASH"
export const MOVE_NOTES_FROM_FOLDER_TO_TRASH = "MOVE_NOTES_FROM_FOLDER_TO_TRASH"
export const DELETE_ALL_NOTES_IN_FOLDER = "DELETE_ALL_NOTES_IN_FOLDER"
export const RENAME_NOTE = "RENAME_NOTE"
export const CHANGE_TEXT = "CHANGE_TEXT"
export const CHANGE_STYLES = "CHANGE_STYLES"

export const CHANGE_MENU_SIZE = "CHANGE_MENU_SIZE"
export const CHANGE_LIST_SIZE = "CHANGE_LIST_SIZE"

export const UPDATE_FROM_CLOUD = "UPDATE_FROM_CLOUD"
