export const SELECT_FOLDER = "SELECT_FOLDER"
export const ADD_FOLDER = "ADD_FOLDER"
export const DELETE_FOLDER = "DELETE_FOLDER"
export const RENAME_FOLDER = "RENAME_FOLDER"

export const SELECT_NOTE = "SELECT_NOTE"
export const ADD_NOTE = "ADD_NOTE"
export const DELETE_NOTE = "DELETE_NOTE"
export const RENAME_NOTE = "RENAME_NOTE"

export const CHANGE_MENU_SIZE = "CHANGE_MENU_SIZE"
export const CHANGE_LIST_SIZE = "CHANGE_LIST_SIZE"
